### PR TITLE
Rbfe updates

### PR DESCRIPTION
**Pull request by annamherz**
Hello! This is the PR related to the updates for the RBFE tutorial.

It addresses the [issue highlighted here](https://github.com/OpenBioSim/BioSimSpaceTutorials/issues/10) and has updated edge data. The cinnabar analysis works with the current cinnabar conda package, version 0.3.0 . All the example outputs are updated to match these.

There is also now added GROMACS RBFE support.

I've removed the outdated fep_archiv entirely.

### CODE REVIEW

**Comment by jmichel80** [comment]
There are tons of conflicts due because https://github.com/OpenBioSim/BioSimSpaceTutorials/pull/19 changed the formatting of the notebooks. 
Rather than resolving all conflicts manually it would make sense to merge this branch, and then apply black and nb-clean to all scripts

**Comment by lohedges** [comment]
I'll just try going on this branch, performing the formatting tweaks, then re-pushing.

**Comment by lohedges** [comment]
This is a pain to resolve either way. Shame that it wasn't merged before my blackening PR (or the opposite). I don't have time to do this today but will try to get around to it soon.

**Comment by annamherz** [comment]
hi! I think the easiest way is for me to make a new branch from the current main and just redo my notebook changes for that and PR that branch as the rest is just file updates. I've started doing that for now on the [rbfe-updates-2](https://github.com/OpenBioSim/BioSimSpaceTutorials/tree/rbfe-updates-2) branch and then I'll PR that one.

**Comment by lohedges** [comment]
Thanks, @annamherz. Apologies for this. Hopefully it's not too painful.

**Comment by annamherz** [comment]
I remembered where most of the changes were so wasn't too bad!

fixed in [rbfe-updates-2](https://github.com/OpenBioSim/BioSimSpaceTutorials/pull/29)

**Pull request closed without merging**
